language: python
matrix:
    include:
        - python: 3.5
          env: TOX_ENV=py35
        - python: 3.6
          env: TOX_ENV=py36
        - python: 3.7
          env: TOX_ENV=py37
install:
    # Install riscv-dv using pip to ensure dependencies are downloaded correctly.
    - pip install -r requirements.txt
    - pip install .
    - pip install tox
script:
    - tox -e $TOX_ENV
    - pip uninstall -y skt
